tests: demostrate crash on nonempty hg incoming when gitnode() is in template
If the user modified his log template to include gitnode(), an invocation of
hg incoming causes a crash with the following message:
    AttributeError: 'overlayrepo' object has no attribute 'githandler'